theme: jekyll-theme-minimal
title: Hey friend, welcome to my website!
description: My name is Vineet, I am currently a student at UCLA. Here you can find links to things I've been working on, and other random musings. Hope you enjoy!
